-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    -   id: black
        name: black
        entry: black
        language: system
        types: [python]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: check-case-conflict
        name: Check case conflict
        description: Check for files with names that would conflict on a case-insensitive filesystem.
        entry: check-case-conflict
        language: system
        types: [python]
    -   id: trailing-whitespace
        name: Trim Trailing Whitespace
        description: This hook trims trailing whitespace.
        entry: trailing-whitespace-fixer
        args: [--markdown-linebreak-ext=md]
        language: python
        types: [text]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.770
    hooks:
    -   id: mypy
        name: mypy
        entry: mypy
        language: python
        types: [python]
        args: ["--ignore-missing-imports", "--scripts-are-modules"]
        require_serial: true
        additional_dependencies: []
